# Number of worker processes to spawn.
# Set to 0 to run everything in a single process without clustering.
# Use ncpu to run as many workers as there are CPU units
num_workers: 0

# Log error messages and gracefully restart a worker if v8 reports that it
# uses more heap (note: not RSS) than this many megabytes.
worker_heap_limit_mb: 250

# Logger info
logging:
  level: trace
#  streams:
#  # Use gelf-stream -> logstash
#    - type: gelf
#        host: logstash1003.eqiad.wmnet
#        port: 12201

# Statsd metrics reporter
metrics:
  type: log
  #host: localhost
  #port: 8125

services:
  - name: cxserver
    # a relative path or the name of an npm package, if different from name
    module: ./app.js
    # optionally, a version constraint of the npm package
    # version: ^0.4.0
    # per-service config
    conf:
      port: 8080
      # interface: localhost # uncomment to only listen on localhost
      # More per-service config settings
      # The location of the spec, defaults to spec.yaml if not specified
      # spec: ./spec.yaml
      # allow cross-domain requests to the API (default *)
      cors: '*'
      # to disable use:
      # cors: false
      # to restrict to a particular domain, use:
      # cors: restricted.domain.org
      # URL of the outbound proxy to use (complete with protocol)
      # proxy: http://my.proxy.org:8080
      # the list of domains for which not to use the proxy defined above
      # no_proxy_list:
      #   - domain1.com
      #   - domain2.org
      # RESTBase API URL
      restbase_url: https://@lang.wikipedia.org/api/rest_v1/page/html/@title
      jwt:
        secret: ''
        algorithms:
          - HS256
      mt:
        # Apertium web API URL
        apertium:
          api: http://apertium.wmflabs.org
        yandex:
          api: https://translate.yandex.net
          key: null
          # SSL certificate of yandex server. Only required while using Node 0.10.x on Ubuntu
          # Setting a value like '/etc/ssl/certs/Certum_Trusted_Network_CA.pem' will help
          # to prevent certificate rejection by nodejs.
          certificate: null
      registry:
        source:
          - ab
          - ace
          - af
          - ak
          - am
          - ang
          - an
          - arc
          - ar
          - arz
          - ast
          - as
          - av
          - ay
          - az
          - bar
          - ba
          - bcl
          - be-tarask
          - be
          - bg
          - bho
          - bi
          - bjn
          - bm
          - bn
          - bo
          - bpy
          - br
          - bs
          - bug
          - bxr
          - ca
          - cbk-zam
          - cdo
          - ceb
          - ce
          - chr
          - ch
          - chy
          - ckb
          - co
          - crh-latn
          - cr
          - csb
          - cs
          - cu
          - cv
          - cy
          - da
          - de
          - diq
          - dsb
          - dv
          - dz
          - ee
          - el
          - eml
          - en
          - eo
          - es
          - et
          - eu
          - ext
          - fa
          - ff
          - fi
          - fj
          - fo
          - frp
          - frr
          - fr
          - fur
          - fy
          - gag
          - gan
          - ga
          - gd
          - glk
          - gl
          - gn
          - gom
          - got
          - gsw
          - gu
          - gv
          - hak
          - ha
          - haw
          - he
          - hif
          - hi
          - hr
          - hsb
          - ht
          - hu
          - hy
          - ia
          - id
          - ie
          - ig
          - ik
          - ilo
          - io
          - is
          - it
          - iu
          - ja
          - jbo
          - jv
          - kaa
          - kab
          - ka
          - kbd
          - kg
          - ki
          - kk
          - kl
          - km
          - kn
          - koi
          - ko
          - krc
          - ksh
          - ks
          - ku
          - kv
          - kw
          - ky
          - lad
          - la
          - lbe
          - lb
          - lez
          - lg
          - lij
          - li
          - lmo
          - ln
          - lo
          - lrc
          - ltg
          - lt
          - lv
          - lzh
          - mai
          - map-bms
          - mdf
          - mg
          - mhr
          - min
          - mi
          - mk
          - ml
          - mn
          - mrj
          - mr
          - ms
          - mt
          - mwl
          - myv
          - my
          - mzn
          - nah
          - nan
          - nap
          - na
          - nds-nl
          - nds
          - ne
          - new
          - nl
          - nn
          - nov
          - no
          - nrm
          - nso
          - nv
          - ny
          - oc
          - om
          - or
          - os
          - pag
          - pam
          - pap
          - pa
          - pcd
          - pdc
          - pfl
          - pih
          - pi
          - pl
          - pms
          - pnb
          - pnt
          - ps
          - pt
          - qu
          - rm
          - rmy
          - rn
          - roa-tara
          - rup
          - ro
          - rue
          - ru
          - rw
          - sah
          - sa
          - scn
          - sco
          - sc
          - sd
          - se
          - sg
          - sgs
          - sh
          - simple
          - si
          - sk
          - sl
          - sm
          - sn
          - so
          - sq
          - srn
          - sr
          - ss
          - stq
          - st
          - su
          - sv
          - sw
          - szl
          - ta
          - tet
          - te
          - tg
          - th
          - ti
          - tk
          - tl
          - tn
          - to
          - tpi
          - tr
          - ts
          - tt
          - tum
          - tw
          - tyv
          - ty
          - udm
          - ug
          - uk
          - ur
          - uz
          - vec
          - vep
          - ve
          - vi
          - vls
          - vo
          - vro
          - war
          - wa
          - wo
          - wuu
          - xal
          - xh
          - xmf
          - yi
          - yo
          - yue
          - za
          - zea
          - zh
          - zu
        target:
          - ab
          - ace
          - af
          - ak
          - am
          - ang
          - an
          - arc
          - ar
          - arz
          - ast
          - as
          - av
          - ay
          - az
          - bar
          - ba
          - bcl
          - be-tarask
          - be
          - bg
          - bho
          - bi
          - bjn
          - bm
          - bn
          - bo
          - bpy
          - br
          - bs
          - bug
          - bxr
          - ca
          - cbk-zam
          - cdo
          - ceb
          - ce
          - chr
          - ch
          - chy
          - ckb
          - co
          - crh-latn
          - cr
          - csb
          - cs
          - cu
          - cv
          - cy
          - da
          - de
          - diq
          - dsb
          - dv
          - dz
          - ee
          - el
          - eml
          - en
          - eo
          - es
          - et
          - eu
          - ext
          - fa
          - ff
          - fi
          - fj
          - fo
          - frp
          - frr
          - fr
          - fur
          - fy
          - gag
          - gan
          - ga
          - gd
          - glk
          - gl
          - gn
          - gom
          - got
          - gsw
          - gu
          - gv
          - hak
          - ha
          - haw
          - he
          - hif
          - hi
          - hr
          - hsb
          - ht
          - hu
          - hy
          - ia
          - id
          - ie
          - ig
          - ik
          - ilo
          - io
          - is
          - it
          - iu
          - ja
          - jbo
          - jv
          - kaa
          - kab
          - ka
          - kbd
          - kg
          - ki
          - kk
          - kl
          - km
          - kn
          - koi
          - ko
          - krc
          - ksh
          - ks
          - ku
          - kv
          - kw
          - ky
          - lad
          - la
          - lbe
          - lb
          - lez
          - lg
          - lij
          - li
          - lmo
          - ln
          - lo
          - lrc
          - ltg
          - lt
          - lv
          - lzh
          - mai
          - map-bms
          - mdf
          - mg
          - mhr
          - min
          - mi
          - mk
          - ml
          - mn
          - mrj
          - mr
          - ms
          - mt
          - mwl
          - myv
          - my
          - mzn
          - nah
          - nan
          - nap
          - na
          - nds-nl
          - nds
          - ne
          - new
          - nl
          - nn
          - nov
          - no
          - nrm
          - nso
          - nv
          - ny
          - oc
          - om
          - or
          - os
          - pag
          - pam
          - pap
          - pa
          - pcd
          - pdc
          - pfl
          - pih
          - pi
          - pl
          - pms
          - pnb
          - pnt
          - ps
          - pt
          - qu
          - rm
          - rmy
          - rn
          - roa-tara
          - rup
          - ro
          - rue
          - ru
          - rw
          - sah
          - sa
          - scn
          - sco
          - sc
          - sd
          - se
          - sg
          - sgs
          - sh
          - simple
          - si
          - sk
          - sl
          - sm
          - sn
          - so
          - sq
          - srn
          - sr
          - ss
          - stq
          - st
          - su
          - sv
          - sw
          - szl
          - ta
          - tet
          - te
          - tg
          - th
          - ti
          - tk
          - tl
          - tn
          - to
          - tpi
          - tr
          - ts
          - tt
          - tum
          - tw
          - tyv
          - ty
          - udm
          - ug
          - uk
          - ur
          - uz
          - vec
          - vep
          - ve
          - vi
          - vls
          - vo
          - vro
          - war
          - wa
          - wo
          - wuu
          - xal
          - xh
          - xmf
          - yi
          - yo
          - yue
          - za
          - zea
          - zh
          - zu
        mt:
          Apertium:
            af:
              - nl
            an:
              - es
            ar:
              - mt
            ast:
              - es
            bg:
              - mk
            ca:
              - en
              - es
              - eo
              - fr
              - oc
              - pt
              - simple
            cy:
              - en
              - simple
            en:
              - ca
              - eo
              - es
              - gl
              - sh
            eo:
              - en
              - simple
            es:
              - an
              - ast
              - ca
              - en
              - eo
              - fr
              - gl
              - it
              - oc
              - pt
              - simple
            eu:
              - en
              - es
              - simple
            fr:
              - ca
              - eo
              - es
            gl:
              - en
              - es
              - simple
            hi:
              - ur
            id:
              - ms
            is:
              - en
              - sv
            it:
              - ca
              - es
            kk:
              - tt
            mk:
              - bg
              - sr
            ms:
              - id
            mt:
              - ar
            nl:
              - af
            nn:
              - da
              - nb
              - no
            no:
              - nn
            oc:
              - ca
              - es
            pt:
              - ca
              - es
              - gl
            ro:
              - es
            sh:
              - en
              - simple
              - sl
            simple:
              - ca
              - eo
              - es
              - gl
              - sh
            sl:
              - sh
              - sr
            sv:
              - da
              - is
            tt:
              - kk
            ur:
              - hi
          Yandex:
            en:
              - ru
        dictionary:
            Dictd:
              en:
                - hi
            JsonDict:
              ca:
                - es
              en:
                - es
              es:
                - ca
